pytest-embedded-idf/pytest_embedded_idf/serial.py
pytest-embedded-idf/tests/test_idf.py
pytest-embedded/pytest_embedded/plugin.py

add `_str_bool()` to change y/yes/true to `True` and n/no/false to `False`
closes #14

feat(idf): add option `--skip-autoflash`

---

README.md
docs/services.md
pytest-embedded/pytest_embedded/dut.py
pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/tests/test_base.py

feat: add `expect_list` and `expect_exact`

---

.gitignore
examples/.gitignore

Don't globally ignore build directory.

---

.github/workflows/python-packages.yml
.pre-commit-config.yaml
pytest-embedded-arduino/setup.py
pytest-embedded-idf/setup.py
pytest-embedded-jtag/setup.py
pytest-embedded-qemu/setup.py
pytest-embedded-serial-esp/setup.py
pytest-embedded-serial/setup.py
pytest-embedded/setup.py

add 3.10 github ci test as well

version: add 3.10 label

---

pytest-embedded-qemu/pytest_embedded_qemu/dut.py

fix(qemu): `dut.write` to qemu process correctly

---

pytest-embedded-qemu/pytest_embedded_qemu/app.py
pytest-embedded/pytest_embedded/plugin.py

Fix: qemu image did not update

---

pytest-embedded-arduino/pytest_embedded_arduino/serial.py
pytest-embedded-idf/pytest_embedded_idf/dut.py
pytest-embedded-idf/pytest_embedded_idf/serial.py
pytest-embedded-jtag/pytest_embedded_jtag/gdb.py
pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
pytest-embedded/pytest_embedded/dut.py
pytest-embedded/pytest_embedded/log.py
pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/tests/test_base.py

this could stop the distraction when the exception is expected.

a bunch of small features and fixes

---

pytest-embedded/pytest_embedded/unity.py
pytest-embedded/tests/test_base.py

fix: unity case name now could include spaces

---

pytest-embedded/pytest_embedded/dut.py
pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/pytest_embedded/utils.py
pytest-embedded/tests/test_base.py

feat: add `expect_all` keyword for `expect` and `expect_exact` functions

---

.pre-commit-config.yaml
pytest-embedded-idf/pytest_embedded_idf/app.py
pytest-embedded-idf/pytest_embedded_idf/serial.py
pytest-embedded-idf/tests/test_idf.py
pytest-embedded/pytest_embedded/plugin.py

Use flash args json to flash

---

pytest-embedded-idf/pytest_embedded_idf/app.py

This PR adds `get_sha256` function which is used to get SHA256 of app

Added get_sha256 function to get SHA256 (RDT-181)

---

.github/workflows/python_tests.yml
docs/requirements.txt
foreach.sh
pyproject.toml
pytest-embedded-arduino/setup.py
pytest-embedded-idf/pytest_embedded_idf/dut.py
pytest-embedded-idf/pytest_embedded_idf/serial.py
pytest-embedded-idf/setup.py
pytest-embedded-idf/tests/test_idf.py
pytest-embedded-jtag/setup.py
pytest-embedded-qemu/setup.py
pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
pytest-embedded-serial-esp/setup.py
pytest-embedded-serial/pytest_embedded_serial/serial.py
pytest-embedded-serial/setup.py
pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/setup.py
requirements.txt

feat(idf): parse coredump automatically

---

docs/services.md
mkdocs.yml
pytest-embedded/pytest_embedded/log.py
pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/pytest_embedded/utils.py

BREAKING CHANGES:
- rename `parse_configuration` to `multi_dut_argument`
- rename `apply_count` to `multi_dut_fixture`
- rename `apply_count_generator` to `multi_dut_generator_fixture`

feat: extract method `parse_multi_dut_args`

---

pytest-embedded-idf/pytest_embedded_idf/app.py
pytest-embedded-idf/pytest_embedded_idf/dut.py
pytest-embedded-idf/pytest_embedded_idf/serial.py
pytest-embedded-idf/tests/test_idf.py

fix(idf): make elf file detection optional

---

pytest-embedded/pytest_embedded/plugin.py

the earlier global variable won't work if fixture `session_tempdir` got overridden.

fix/record session_tempdir into config.stash

---

pytest-embedded-idf/pytest_embedded_idf/dut.py
pytest-embedded-idf/tests/test_idf.py

Add a function to get test case list from test menu via UART print. 
Input:
```
(54)	"sdio interrupt" [sdio][test_env=UT_SDIO][multi_device]
(1)	"test_sdio_interrupt_master"
(2)	"test_sdio_interrupt_slave"
(55)	"sdio register" [sdio][test_env=UT_SDIO][multi_device]
(1)	"test_sdio_reg_master"
(2)	"test_sdio_interrupt_slave"
(56)	"sdio reset" [sdio][test_env=UT_SDIO][multi_device]
(1)	"test_sdio_reset_master"
(2)	"test_sdio_reset_slave"
(57)	"master slave test: SDIO_FRHOST" [sdio][timeout=180][test_env=UT_SDIO][multi_device]
(1)	"PTEST_MASTER_SDIO_FRHOST"
(2)	"PTEST_SLAVE_SDIO_FRHOST"
(58)	"master slave test: SDIO_TOHOST" [sdio][timeout=180][test_env=UT_SDIO][multi_device]
(1)	"PTEST_MASTER_SDIO_TOHOST"
(2)	"PTEST_SLAVE_SDIO_TOHOST"
```
Output:
```
UnittestMenuCase(index=54, name='sdio …
```

feat(idf): add function to parse case list from unit test menu (RDT-243)

---

pytest-embedded/pytest_embedded/unity.py
pytest-embedded/tests/test_base.py

fix: merge junit report error when multi-dut

---

pytest-embedded-idf/pytest_embedded_idf/serial.py

fix(esp): file stream keep open when exception is raised

---

pytest-embedded-serial/pytest_embedded_serial/dut.py
pytest-embedded-serial/pytest_embedded_serial/serial.py

inject pyserial.Serial methods. Use event loop to run the real serial commands

---

pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
pytest-embedded-serial/pytest_embedded_serial/serial.py
pytest-embedded/pytest_embedded/plugin.py

- Added support for binding ports based on the location of a USB device
Closes https://github.com/espressif/pytest-embedded/issues/118

feat: Added support for binding ports based on the USB device location

---

.github/workflows/python_tests.yml

This reverts commit dcaeb1a490f8fc1c5da67c09e4d84d59901cf551.

Revert "temp: workaround to install esptool correctly"

---

pytest-embedded-idf/pytest_embedded_idf/dut.py
pytest-embedded-jtag/tests/test_jtag.py
pytest-embedded-serial/pytest_embedded_serial/dut.py
pytest-embedded/pytest_embedded/plugin.py

sometimes gdb instance would halt the target

feat(jtag): add cli option `--no-gdb` to stop create gdb instance automatically

---

pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/tests/test_base.py

Added test case name uniqueness validation

fix: Added test case name uniqueness validation

---

pytest-embedded/pytest_embedded/plugin.py
pytest-embedded/tests/test_base.py

#157 add this functionality but it would be a breaking change.

feat: add "--check-duplicates" cli option

---

pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
pytest-embedded-idf/tests/test_idf.py
pytest-embedded/pytest_embedded/plugin.py

#153 forgot to add this as a fixture.

feat(idf): add fixture `unity_tester` to test multi device unity test cases

---

pytest-embedded/pytest_embedded/plugin.py

- prettify xml junit report
close #165

feature: prettify xml junit report

---

pytest-embedded-idf/pytest_embedded_idf/__init__.py
pytest-embedded-idf/pytest_embedded_idf/dut.py

also keep backward compatibility

feat: expose pytest_embedded_idf.UnittestMenuCase

---

.github/workflows/test-python.yml
README.md
docs/api.rst
docs/conf.py
docs/expecting.md
docs/key_concepts.md
docs/services.md
pytest-embedded-wokwi/README.md

docs: add missing documentation for wokwi

---

pytest-embedded-wokwi/README.md
pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
pytest-embedded/pytest_embedded/plugin.py

feat(wokwi): support for specifying simulation timeout

---

pytest-embedded/pytest_embedded/dut_factory.py

fix: remove required optional dependencies 'idf'

---

pytest-embedded-jtag/pytest_embedded_jtag/gdb.py

In many test logs, I see a 'gdb no response' error. As I understand, this occurs due to a loss of synchronization between what we actually send and what is inside the response file. With this PR, we will ensure that before the first command, there will be no unevaluated response in the queue.
I also made some small changes that seem more logical to me.

fix(jtag): flush previous gdb responses before the first gdb command (RDT-857)

---

.pre-commit-config.yaml
pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py

fix(wokwi): pexpect.spawn not working on windows. use subprocess instead

---

pytest-embedded-jtag/pytest_embedded_jtag/__init__.py
pytest-embedded-jtag/pytest_embedded_jtag/_telnetlib/LICENSE
pytest-embedded-jtag/pytest_embedded_jtag/_telnetlib/telnetlib.py
pytest-embedded-jtag/pytest_embedded_jtag/openocd.py
pytest-embedded-serial/pytest_embedded_serial/dut.py
ruff.toml

Refactor: pull telnetlib from python

---

docs/concepts/services.md
pytest-embedded-nuttx/README.md
pytest-embedded-nuttx/pyproject.toml
pytest-embedded-nuttx/pytest_embedded_nuttx/__init__.py
pytest-embedded-nuttx/pytest_embedded_nuttx/app.py
pytest-embedded-nuttx/pytest_embedded_nuttx/dut.py
pytest-embedded/pytest_embedded/dut_factory.py

This PR improves the Nuttx service by adding support for QEMU.
It also modifies the reset functionality to support serial reset (DTR toggle), QEMU reset and ESP reset.
On a different topic, there's a smaller commit to improve logging on app binary search.
None.
Tested locally running qemu applications.
---
Looking forward to any improvements.

Add QEMU support for NuttX service (RDT-1034)

---

LICENSE

chore: add license for the repo
