espressif/pytest-embedded

- pytest-embedded-idf/pytest_embedded_idf/serial.py
> fix: raise idf app not parsable error if binary path not parsable

- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
> fix(esp): esptool wrong boot mode issue

- pytest-embedded-idf/tests/test_idf.py
- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
the redirect_io_thread is always reading from serial, need to disconnect and reconnect first!
> Fix stub loader can never read serial issue

- pytest-embedded-idf/pytest_embedded_idf/app.py
- pytest-embedded/pytest_embedded/dut.py
- pytest-embedded/tests/test_base.py
sometimes the current buffer would be too long to track. use textwrap
to make it readable.
> fix: improve debug string

- pytest-embedded-idf/pytest_embedded_idf/serial.py
Added erase_flash and erase_partition functionality to pytest embedded
> pytest_embedde_idf/serial.py: Added erase_flash and erase_partition (RDT-197)

- pytest-embedded-idf/pytest_embedded_idf/app.py
This MR fixes esptool imports.
https://github.com/espressif/pytest-embedded/pull/77#discussion_r834197044
> Fix esptool imports (RDT-222)

- foreach.sh
1. Add the bash shebang
2. Add the rest of the usual options that go with set -e (`set -euo pipefail`)
3. make the file executable.
> foreach.sh: Update the script

- pytest-embedded-arduino/pytest_embedded_arduino/serial.py
- pytest-embedded-idf/pytest_embedded_idf/serial.py
- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded/pytest_embedded/plugin.py
Add an option to erase the flash before programming. And example that needs this is: https://github.com/espressif/arduino-esp32/pull/6916
Tested with the Arduino example by adding:
```diff
diff --git a/examples/arduino/hello_world/test_hello_world.py b/examples/arduino/hello_world/test_hello_world.py
index 0e7cea8..03f7346 100644
--- a/examples/arduino/hello_world/test_hello_world.py
+++ b/examples/arduino/hello_world/test_hello_world.py
@@ -1,2 +1,9 @@
+import pytest
+
+@pytest.mark.parametrize(
+    'erase_flash',
+    ['True'],
+    indirect=True,
+)
def test_hello_arduino(dut):
dut.expect('Hello Arduino!')
```
IDF service added a similar function bu I am not sure how that one is used.
> Add erase-flash option to erase the flash before programming. (RDT-234)

- pytest-embedded-arduino/pytest_embedded_arduino/serial.py
- pytest-embedded-idf/pytest_embedded_idf/serial.py
- pytest-embedded-idf/tests/test_idf.py
- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded/pytest_embedded/plugin.py
fix regression from https://github.com/espressif/pytest-embedded/pull/98
> fix cli option "--erase-flash" conflict with function `erase_flash()`

- pytest-embedded/pytest_embedded/plugin.py
pytest docs say that fixtures can be overridden: 
https://docs.pytest.org/en/latest/how-to/fixtures.html?highlight=override#override-a-fixture-on-a-test-module-level
When I override the `dut` fixture in a module, it still gets caught by this `pytest_embedded` hook.
This change explicitly checks that the dut is of type `pytest_embedded.dut.Dut`
> only hook on dut of type pytest_embedded.dut.Dut

- README.md
The current link to `docs.espressif.com` is not working due to a missing slash at the end.
> Fix link to docs.espressif.com

- mkdocs.yml
related #127 
sphinx theme is highly binded to sphinx project. can't use that theme directly.
After changing the theme from `material` to `readthedocs` the layout turn out to be:
> docs: use readthedocs theme

- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded-serial/pytest_embedded_serial/serial.py
- pytest-embedded/pytest_embedded/plugin.py
- Added support for binding ports based on the MAC address of the board
Closes https://github.com/espressif/pytest-embedded/issues/117
> feat: Added support for binding ports based on the MAC address of the board

- pytest-embedded-idf/pytest_embedded_idf/dut.py
- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded-serial/pytest_embedded_serial/dut.py
- pytest-embedded-serial/pytest_embedded_serial/serial.py
trade off to #67 
1. we need direct access to pyserial instance
2. pyserial object cannot be pickled
3. since it's using file descriptor, `NamespaceProxy` won't work for windows as well
can use thread only...
> fix(serial): use thread for serial

- pytest-embedded-serial/pytest_embedded_serial/serial.py
RFC2217 enables remote serial ports over TCP. It's supported by esptool and even [documented](https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/remote-serial-ports.html#remote-serial-ports). 
This fix allows using RFC2217 ports with pytest-embedded.
> Support rfc2217 connections

- pytest-embedded-arduino/pytest_embedded_arduino/app.py
- pytest-embedded-arduino/pytest_embedded_arduino/serial.py
I have separated flash_setting for each SoC, as the H2 cannot flash on default 80MHz.
Tested locally on H2.
> pytest_embedded_arduino/: Separated flash settings for each target to fix H2

- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded-serial-esp/tests/test_esp.py
- pytest-embedded/pytest_embedded/plugin.py
Implement local cache for port-target-cache between session with use shelve.
Change function port_target_cache to yield fixtures type.
closes #182
> local cache for port-target-cache between session (RDT-501)

- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
The method `hard_reset()` of the class `EspSerial` used the default arguments of the decorator use_esptool(), due to which stub is required for performing a hard_reset().
This support for `no_stub` allows usage of the package with the newer chips for whom `flasher_stub` support has not been added yet.
> feat: Support hard_reset without stub (RDT-542)

- foreach.sh
- pytest-embedded-wokwi/LICENSE
- pytest-embedded-wokwi/README.md
- pytest-embedded-wokwi/pyproject.toml
- pytest-embedded-wokwi/pytest_embedded_wokwi/__init__.py
- pytest-embedded-wokwi/pytest_embedded_wokwi/dut.py
- pytest-embedded-wokwi/pytest_embedded_wokwi/idf.py
- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
- pytest-embedded-wokwi/tests/test_wokwi.py
- pytest-embedded/pytest_embedded/plugin.py
- pytest-embedded/pytest_embedded/utils.py
Functional implementation draft. Tested with https://github.com/espressif/gh-esp-test-template on simulated ESP32C6.
<strike>The Wokwi CLI still has no support for specifying multiple flash images. You can either give it an application binary file or elf file to load at 0x10000, using a default bootloader and partition table, or specify a full flash image to load. I'm still trying to figure out what's the best way to address it. Meanwhile, we only provide the app image to the CLI as a workaround.</strike>
Also, we can automatically download the CLI for the user, in case it's not installed. Not sure if this is a good idea, and where we should install it. It's distributed as a single binary, and currently [supports](https://github.com/wokwi/wokwi-cli/releases/tag/v0.6.7) Linux (arm, x64), …
> feature: Wokwi simulation support (RDT-551)

- pytest-embedded-serial/tests/test_serial.py
- pytest-embedded/pytest_embedded/plugin.py
Running pytest with these arguments, along with pytest-lazy-fixture, can lead to a file descriptor error: 'ValueError: filedescriptor out of range in select()'.
-s --count 2 --embedded-services serial --port  /dev/ttyUSB0|/dev/ttyUSB1 --baud=115200|115200
The current commit helps alleviate this error, but if there are a large number of tests, the file descriptor error still exists.
close #232
> fix(serial.py): Pytest-embedded leaks file descriptors when used with pytest-lazy-fixture (RDT-577)

- pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
- pytest-embedded-idf/tests/test_idf.py
Replaced logic of creating thread
before: new case every time create new thread
now: create thread once, and then thread wait for task
closes #184
closes #162
> refactor: change logic of threading control in CaseTester for MultiDev (RDT-534)

- conftest.py
Remove the cache to make testing pytest-embedded more stable.
> feat: remove cache file when tests pytest-embedded itself

- pytest-embedded-idf/pyproject.toml
- pytest-embedded-idf/pytest_embedded_idf/dut.py
- pytest-embedded/pytest_embedded/plugin.py
Import `gdb_panic_server.py from esp_idf_panic_decoder` and use it instead of the static `$IDF_PATH/tools/gdb_panic_server.py` path.
closes #225
> feat: gdb panic server from module (RDT-606)

- pytest-embedded-qemu/pytest_embedded_qemu/qemu.py
In CI tested internally, we're facing errors like
```
/root/.espressif/python_env/idf5.3_py3.8_env/lib/python3.8/site-packages/pytest_embedded/plugin.py:458: in wrapper
res = func(*args, **kwargs)
/root/.espressif/python_env/idf5.3_py3.8_env/lib/python3.8/site-packages/pytest_embedded/plugin.py:1379: in qemu
return cls(**_drop_none_kwargs(kwargs))
/root/.espressif/python_env/idf5.3_py3.8_env/lib/python3.8/site-packages/pytest_embedded_qemu/qemu.py:64: in __init__
self.qmp = QMPClient()
/root/.espressif/python_env/idf5.3_py3.8_env/lib/python3.8/site-packages/qemu/qmp/qmp_client.py:247: in __init__
Events.__init__(self)
/root/.espressif/python_env/idf5.3_py3.8_env/lib/python3.8/site-packages/qemu/qmp/events.py:656: in __init__
self.events: EventListener = EventListener() …
```
> fix(qemu): fix qmp client missing event loop in main thread

- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
We now have ESP32-P4 support in Wokwi!
It is still a preview release, but it's functional enough to run tests. I ran a quick test on my system, here is the complete output:
```
(pytest-new) PS C:\p\wokwi-esp-test-template\test_app> pytest --target=esp32p4 --embedded-services idf,wokwi
============================================== test session starts ===============================================
platform win32 -- Python 3.8.10, pytest-7.4.4, pluggy-1.3.0
rootdir: C:\p\wokwi-esp-test-template\test_app
configfile: pytest.ini
plugins: embedded-1.6.1
collected 1 item
test_app.py::test_app
------------------------------------------------- live log setup ------------------------------------------------- 
2024-01-11 00:32:42 INFO Executing wokwi-cli C:\p\wokwi-esp-test-template\test_app …
```
> feature: Preliminary esp32p4 support in Wokwi

- .github/workflows/test-python.yml
- pytest-embedded-qemu/pytest_embedded_qemu/qemu.py
- pytest-embedded-qemu/tests/test_qemu.py
While running the test, we encountered a conflict with port allocation. The current PR is an attempt to resolve this issue.
> fix: use socket bind to get allowed port

- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
see https://github.com/espressif/pytest-embedded/issues/233#issuecomment-1893741907 for details.
Note: this fix requires updating wokwi-cli to the latest version, 0.9.0. For people using this in CI, the latest version should be installed automatically.
> fix(wokwi): run in interactive mode

- pytest-embedded-arduino/pytest_embedded_arduino/serial.py
- pytest-embedded-idf/pytest_embedded_idf/serial.py
- pytest-embedded-idf/tests/test_idf.py
- pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
- pytest-embedded/pytest_embedded/plugin.py
- This PR replaced the use of the esptool functions with `esptool.main`.
- Added the flag '--esp-flash-force' for 'force mode for esptool'.
closes #235
> ref: use esptool main instead other func

- pytest-embedded/pytest_embedded/unity.py
In this PR, the log level in utils.py was changed to 'debug' to remove redundant information.
> fix(utils): change log level to debug

- pytest-embedded-idf/pytest_embedded_idf/serial.py
Set the baud rate to 1,000,000 to make the flash faster when no value is set up. 
Closes #268.
> fix: flash baud

- pytest-embedded-idf/pytest_embedded_idf/serial.py
Caused errors while not explicitly providing the ESPBAUD environment variable due to non-standard default baud rate.
<details>
<summary>Click here to expand the traceback (not for the faint of heart)</summary>
```pytb
Detecting the Python interpreter
Checking "python3" ...
Python 3.8.10
"python3" has been detected
Checking Python compatibility
Checking other ESP-IDF version.
Adding ESP-IDF tools to PATH...
Checking if Python packages are up to date...
The following Python requirements are not satisfied:
Requirement 'pytest-embedded-idf~=0.8' was not met. Installed version: 1.8.3
Requirement 'protobuf<=3.20.1' was not met. Installed version: 5.26.1
Requirement 'pytest-embedded-qemu~=0.8' was not met. Installed version: 1.8.3
Requirement 'idf-build-apps~=1.0' was not met. Installed version: …
```
> fix: non-standard default baud rate

- pytest-embedded-idf/tests/test_idf.py
- pytest-embedded-serial/tests/test_serial.py
- pytest-embedded/pytest_embedded/__init__.py
- pytest-embedded/pytest_embedded/dut_factory.py
- pytest-embedded/pytest_embedded/plugin.py
- pytest-embedded/pytest_embedded/utils.py
- created factory class for dut
closes #231
> feat: create dut-factory method (RDT-587)

- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
- pytest-embedded/pytest_embedded/dut_factory.py
- pytest-embedded/pytest_embedded/plugin.py
This PR adds a support of scenario file for Pytest-wokwi.
To use scenario file add `--wokwi_scenario <path>` to the pytest command
> feat(wokwi): Add scenario path parameter

- pytest-embedded/pytest_embedded/plugin.py
- pytest-embedded/tests/test_base.py
related https://github.com/pytest-dev/pytest/pull/12277
> feat(esp): support add target as marker ('|' will be escaped to '-')

- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
Fixes wrong paths (or unsupported paths) for binary and elf files for Wokwi.
> fix(wokwi): Fix paths for bin and elf files

- pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
- pytest-embedded-idf/tests/test_idf.py
This MR implements a feature for dry running single board Unity tests, allowing users to display a list of test case names without actually running them when the `dry_run` parameter in `run_all_single_board_cases` is set to True.
> feat: dry run single board unity test

- pytest-embedded-wokwi/pytest_embedded_wokwi/__init__.py
- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi_cli.py
- pytest-embedded-wokwi/tests/test_wokwi.py
- pytest-embedded/pytest_embedded/dut_factory.py
- pytest-embedded/pytest_embedded/plugin.py
This PR adds a support of specifying diagram file for pytest-embedded-wokwi. 
To specify diagram.json add --wokwi-diagram to the pytest command
> feat(wokwi): Add support for specifying diagram path

- pytest-embedded-serial/pytest_embedded_serial/dut.py
This reverts commit fd1f21974c7c9e0c2ad1fd81b9c8a4e9650ebb26.
> Revert "fix(jtag): gdb write "remotetimeout" stop waiting for response"

- pytest-embedded-arduino/pytest_embedded_arduino/app.py
Add missing ESP32-P4 information to `pytest-embedded-arduino`.
Please confirm if the information provided is correct and is the only changes required to make P4 work.
Thanks in advance.
Local and CI
> Add P4 to pytest-embedded-arduino

- pytest-embedded-idf/pytest_embedded_idf/app.py
- pytest-embedded-qemu/pytest_embedded_qemu/app.py
- pytest-embedded-qemu/pytest_embedded_qemu/qemu.py
Get the qemu program path by target
> Fix: qemu toolchain path

- pytest-embedded-wokwi/pytest_embedded_wokwi/arduino.py
Arduino tests in Wokwi will fallback to a default bootloader and partition table if none is provided. This can cause issues with some tests. To make sure the partition table and bootloader are always flashed, we need to use the generated merged image by the Arduino compilation.
Tested locally, works as expected.
> fix(wokwi): Use merged bin to ensure partition and bootloader flashing

- pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
- pytest-embedded-idf/tests/test_idf.py
- pytest-embedded/pytest_embedded/plugin.py
- pytest-embedded/pytest_embedded/unity.py
1. **Introduced the `--unity-test-report-mode` Flag**
- **Behavior**:
- When enabled, Python test cases are retained in the JUnit report alongside detailed test cases (e.g., C test cases).
- By default, Python test cases are replaced by detailed test cases in the report.
- **Purpose**:
- Helps maintain clarity by allowing both Python and C test cases in the report.
2. **Added the `is_unity_case` Attribute to Test Cases**
- **Details**:
- `is_unity_case="1"`: Indicates a Python test case.
- `is_unity_case="0"`: Indicates a non-Python test case (e.g., C test case).
- **Impact**:
- Improves clarity and traceability of test cases in the JUnit report.
---
1. **Fixed Inconsistent `line` and `file` Attributes in XML Reports**
- Removed `[dut-X]` prefixes from `line` and `file` attributes in the …
> feat(junit-merger): add flag to preserve Python test cases and "is_unity_case" attribute

- pytest-embedded/pytest_embedded/dut_factory.py
Under heavy loads, the `_listen()` function produces truncated or corrupted log output.
Example test:
In a normal sequence, each log line should contain a contiguous block of data like `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/`. 
However, in the snippet below, we see a break in the expected pattern:
```
2025-01-19 23:02:17 7b40::ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
2025-01-19 23:02:17 7b80::ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
2025-01-19 23:02:17 7bc0::ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
2025-01-19 23:02:17 7c00::ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
2025-01-19 23:02:17 7c40::ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/
2025-01-19 …
```
> Fix Missing Serial Data Under Heavy Load (RDT-1099)

- pytest-embedded/pytest_embedded/dut_factory.py
- pytest-embedded/pytest_embedded/log.py
> fix: read all chunks in queue since we have interval in listener

- docs/usages/markers.rst
- pytest-embedded-idf/pytest_embedded_idf/unity.py
- pytest-embedded-idf/pytest_embedded_idf/utils.py
- pytest-embedded-idf/tests/test_idf.py
Add idf_parametrize decorator to simplify pytest parametrization by handling target expansion and runner marks via string representation.
- Automatically expanding special target values ('supported_targets' and 'preview_targets') into individual test cases;
- Simplifying pytest mark usage by allowing string-based mark definitions instead of direct pytest.mark usage;
- Unifying the parametrization pattern across esp-idf test cases;
---
> feat: parametrize_wrapper

- pytest-embedded-qemu/pytest_embedded_qemu/app.py
Running a pytest test case using QEMU for ESP32-C3, produces the following error:
```
2025-02-27 20:22:56 INFO Executing qemu-system-riscv32 -nographic -machine esp32c3 -qmp tcp:127.0.0.1:53445,server,wait=off -drive file=/Users/harshal/esp/esp-idf/tools/test_apps/security/secure_boot/test/esp32c3_efuses.bin,if=none,format=raw,id=efuse -global driver=nvram.esp32c3.efuse,property=drive,value=efuse -global driver=timer.esp32c3.timg,property=wdt_disable,value=true -drive file=/Users/harshal/esp/esp-idf/tools/test_apps/security/secure_boot/build/flash_image.bin,if=mtd,format=raw
2025-02-27 20:22:56 esptool.py v4.9.dev5
2025-02-27 20:22:56 SHA digest in image updated
2025-02-27 20:22:56 Wrote 0x80000 bytes to file /Users/harshal/esp/esp-idf/tools/test_apps/security/secure_boot/build/flash_image …
```
> fix(pytest-embedded-qemu): Allowed QEMU RISCV flash image sizes (RDT-1177)

- pytest-embedded-idf/pytest_embedded_idf/utils.py
- pytest-embedded-idf/tests/test_idf.py
In this PR, a function is added that will return a target list according to the **SOC_CAPS** attribute. We already have `skip_if_soc`, but in some cases, it is better to directly filter by target rather than adding a skip mark for it.
The `test_soc_filtered_targets` was added.
> feat: get targets filtered by soc attrs

- docs/usages/markers.rst
- pytest-embedded-idf/pytest_embedded_idf/utils.py
- pytest-embedded-idf/tests/test_idf.py
Update the documentation for the `soc_filtered_targets` function and add support for choosing between target sets.
#345 
> Target Set Selection Support (soc_filtered_targets)

- pytest-embedded-nuttx/pytest_embedded_nuttx/serial.py
This PR adds an exception for flash mode when in QIO/QOUT mode, defaulting to DIO.
It follows the following description on ESP-IDF, which can be found [here](https://github.com/espressif/esp-idf/blob/194ea85ee82e65ec1b9236225425540a61754201/components/esptool_py/Kconfig.projbuild#L79):
```
```
Before this fix, the device enters a boot loop after flashing:
```
2025-04-16 15:47:58 Hard resetting via RTS pin...
INFO:root:Resetting board
Hard resetting via RTS pin...
2025-04-16 15:47:58 ESP-ROM:esp32h2-ESP-ROM:esp32h2-20221101
2025-04-16 15:47:58 Build:Nov  1 2022
2025-04-16 15:47:58 rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
2025-04-16 15:47:58 SPIWP:0xee
2025-04-16 15:47:58 mode:QOUT, clock div:1
2025-04-16 15:47:58 load:0x40800000,len:0x5354
2025-04-16 15:47:58 ets_loader.c 64 …
```
> fix: flash mode exception on Nuttx (RDT-1276)

- pytest-embedded-nuttx/pytest_embedded_nuttx/serial.py
- pytest-embedded/pytest_embedded/dut_factory.py
This PR modifies the NuttxSerial class.
It had a fixed flash baud rate (for Espressif devices) and now it can be changed through the command line. It simply removes the custom entry for baud rate and uses the baud from the inherited EspSerial class.
Tested by running Pytest without setting `--esptool-baud` and than by setting to a customized value.
The flash is first erased and then the firmware is uploaded. Baud rate line is marked.
- Without setting `esptool-baud`:
```
==========================================
INFO:root:Flashing device
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.12.3, pytest-8.3.4, …
```
> feat: use baudrate from EspSerial in EspNuttx (RDT-1275)

- pytest-embedded-idf/pytest_embedded_idf/dut.py
- tests/fixtures/hello_world_linux/build/project_description.json
- tests/fixtures/unit_test_app_linux/build/project_description.json
Rename `prefix_map_gdbinit` to `gdbinit/prefix_map`
- IDF MR !41549
- IDF-11667
---
> change: rename prefix_map_gdbinit to gdbinit/prefix_map (RDT-1461)

- pytest-embedded-qemu/pytest_embedded_qemu/app.py
> fix(qemu): set `qemu_proj_path` for `QemuApp` correctly

- pytest-embedded-qemu/pytest_embedded_qemu/qemu.py
- pytest-embedded-qemu/tests/test_qemu.py
- pytest-embedded-wokwi/pytest_embedded_wokwi/wokwi.py
- pytest-embedded/pytest_embedded/dut_factory.py
- pytest-embedded/pytest_embedded/plugin.py
> feat: add support for efuse in qemu
